site_name: AnatoQuizUp
site_description: AnatoQuizUp é um jogo de perguntas e respostas sobre anatomia humana, desenvolvido para ajudar estudantes de medicina a aprenderem de forma divertida e interativa.

theme:
  name: material
  language: pt-BR
  features:
      - navigation.tabs
    
nav:
  - Início: index.md
  - Produto:
    - Visão do Produto: produto/visao.md
    - Lean Inception: produto/lean_inception.md
  - Backlog:
    - Visão Geral: backlog/overview.md
    - Histórias e Tarefas:
      - Release Major 1: backlog/release-major-1.md
      - Release Major 2: backlog/release-major-2.md
      - Release Major 3: backlog/release-major-3.md
  - Arquitetura:
    - Visão Geral: arquitetura/visao_geral.md
    - Tecnologias: arquitetura/tecnologias.md
    - Decisões Arquiteturais: arquitetura/decisoes.md
    - Visões Arquiteturais:
      - Visão Lógica: arquitetura/visoes/logica.md
      - Visão de Processos: arquitetura/visoes/processos.md
      - Visão de Implementação: arquitetura/visoes/implementacao.md
      - Visão de Implantação: arquitetura/visoes/implantacao.md
    - Banco de Dados:
      - Versão 1: arquitetura/banco-de-dados/v1.md
  - Protótipos: prototipo/figma.md
  - Projeto e Processo:
    - Roadmap e Releases: processo/roadmap.md
    - Sprints: processo/sprints.md
    - Reuniões: processo/reunioes.md
    - Atas: processo/atas.md
    - Metodologia e DoD: processo/metodologia.md
  - Qualidade e Métricas:
    - Métricas e Dashboard: qualidade/qualidade.md
  - Decisões:
    - Decisões do Projeto: decisoes/decisoes.md
  - Contribuição: 
    - Código de Conduta: contribuicao/codigo_conduta.md
    - Política de Branchs: contribuicao/politica_branchs.md
    - Política de Commits: contribuicao/politica_commits.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format